<script setup lang="ts">
import { computed, ref } from 'vue';
export type TableStatus = 'AVAILABLE'|'OCCUPIED'|'RESERVED'|'HELD'|'CLEANING'|'OUT_OF_SERVICE';
export interface RestaurantTable { id:number; tableNumber:string; tableName:string; capacity:number; tableType:string; section?:string|null; status:TableStatus; heldBy?:string|null; holdExpiresAt?:string|null; }
const props=defineProps<{tables:RestaurantTable[]; modelValue:number|''; guestCount?:number}>();
const emit=defineEmits<{ 'update:modelValue':[value:number|''] }>();
const open=ref(false), search=ref(''), filter=ref<'ALL'|TableStatus>('ALL');
const selected=computed(()=>props.tables.find(t=>t.id===props.modelValue));
const options=computed(()=>[...props.tables].filter(t=>filter.value==='ALL'||t.status===filter.value).filter(t=>`${t.tableNumber} ${t.tableName} ${t.tableType}`.toLowerCase().includes(search.value.toLowerCase())).sort((a,b)=>Number((props.guestCount||0)>0&&a.capacity>=(props.guestCount||0))-Number((props.guestCount||0)>0&&b.capacity>=(props.guestCount||0))||a.tableNumber.localeCompare(b.tableNumber)).reverse());
function disabled(t:RestaurantTable){return t.status==='OCCUPIED'||t.status==='RESERVED'||t.status==='CLEANING'||t.status==='OUT_OF_SERVICE'||t.status==='HELD';}
function select(t:RestaurantTable){if(disabled(t))return;emit('update:modelValue',t.id);open.value=false;}
function detail(t:RestaurantTable){if(t.status==='HELD'&&t.holdExpiresAt)return `Held until ${new Date(t.holdExpiresAt).toLocaleTimeString([], {hour:'numeric',minute:'2-digit'})}`;return t.status.replaceAll('_',' ');}
</script>
<template><div class="table-selector"><button type="button" class="selector-trigger" @click="open=!open" :aria-expanded="open"><span v-if="selected"><strong>{{ selected.tableNumber }}</strong> · {{ selected.tableName }} · {{ selected.capacity }} seats</span><span v-else>Select table</span><span>⌄</span></button><div v-if="open" class="selector-popover"><input v-model="search" autofocus placeholder="Search table or section…" /><div class="table-filters"><button v-for="item in ['ALL','AVAILABLE','OCCUPIED','RESERVED','HELD']" :key="item" :class="{active:filter===item}" @click="filter=item as any">{{ item==='ALL'?'All':item[0]+item.slice(1).toLowerCase() }}</button></div><div class="table-options"><button v-for="table in options" :key="table.id" type="button" class="table-option" :class="[{selected:table.id===modelValue,disabled:disabled(table)},table.status.toLowerCase()]" :disabled="disabled(table)" @click="select(table)"><span class="table-option-main"><strong>{{table.tableNumber}}</strong><span>{{table.tableName}} · {{table.tableType}}</span></span><span class="table-option-meta"><span class="capacity-badge">{{table.capacity}} seats</span><span class="table-status">● {{ detail(table) }}</span></span></button><p v-if="!options.length" class="no-tables">No matching tables.</p></div></div></div></template>
<style scoped>.table-selector{position:relative}.selector-trigger{width:100%;display:flex;justify-content:space-between;align-items:center;border:1px solid var(--line);border-radius:10px;background:#fff;padding:11px 12px;color:var(--ink);text-align:left}.selector-popover{position:absolute;z-index:20;width:min(440px,100%);margin-top:6px;padding:10px;background:var(--paper);border:1px solid var(--line);border-radius:12px;box-shadow:0 14px 30px rgba(36,33,27,.18)}.selector-popover input{width:100%;border:1px solid var(--line);border-radius:8px;padding:10px;background:#fff}.table-filters{display:flex;gap:5px;overflow:auto;padding:9px 0}.table-filters button{border:0;border-radius:999px;padding:5px 9px;background:transparent;color:var(--ink-soft);font-size:11px}.table-filters button.active{background:var(--char);color:var(--paper)}.table-options{max-height:310px;overflow:auto}.table-option{width:100%;padding:11px 6px;display:flex;align-items:center;justify-content:space-between;gap:10px;border:0;border-top:1px solid var(--line);background:transparent;text-align:left;color:var(--ink)}.table-option:hover:not(:disabled),.table-option.selected{background:rgba(217,119,6,.09)}.table-option.disabled{opacity:.52;cursor:not-allowed}.table-option-main,.table-option-meta{display:flex;flex-direction:column;gap:3px}.table-option-main span,.table-option-meta{font-size:11px;color:var(--ink-soft)}.capacity-badge{align-self:flex-end;border-radius:999px;padding:2px 7px;background:var(--paper-dim);color:var(--ink)}.table-status{font-size:11px}.available .table-status{color:var(--sage)}.occupied .table-status{color:var(--rust)}.reserved .table-status,.held .table-status{color:var(--ember)}.no-tables{font-size:12px;color:var(--ink-soft)}</style>
