package com.restro.restaurantservice.service;
import com.restro.restaurantservice.domain.entity.*; import com.restro.restaurantservice.domain.enums.*; import com.restro.restaurantservice.domain.exception.*; import com.restro.restaurantservice.repository.*; import com.restro.restaurantservice.web.dto.*; import java.time.*; import java.util.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service public class TableService {
 private final RestaurantTableRepository tables; private final ReservationRepository reservations; private final RestaurantOrderRepository orders;
 public TableService(RestaurantTableRepository tables,ReservationRepository reservations,RestaurantOrderRepository orders){this.tables=tables;this.reservations=reservations;this.orders=orders;}
 @Transactional public List<TableResponse> list(Integer capacity){expireHolds(); return tables.findByActiveTrueOrderByTableNumberAsc().stream().filter(t->capacity==null||t.getCapacity()>=capacity).map(this::table).toList();}
 @Transactional(readOnly=true) public TableResponse get(Long id){return table(find(id));}
 @Transactional public TableResponse create(TableRequest r){ if(tables.findByTableNumber(r.tableNumber().trim()).isPresent()) throw new BusinessRuleException("Table number already exists."); RestaurantTable t=new RestaurantTable(); apply(t,r,false); t.setStatus(TableStatus.AVAILABLE); t.setActive(true); return table(tables.save(t)); }
 @Transactional public TableResponse update(Long id,TableRequest r){RestaurantTable t=find(id); boolean activeOrder=hasActiveOrder(t); if(activeOrder && (t.getCapacity()!=r.capacity()||!t.getTableNumber().equals(r.tableNumber())||r.status()!=TableStatus.OCCUPIED||Boolean.FALSE.equals(r.active()))) throw new BusinessRuleException("This table has an active order. Complete or transfer the order before changing its structure, status, or activation."); apply(t,r,true);return table(t);}
 @Transactional public TableResponse hold(Long id,HoldTableRequest r,String user){RestaurantTable t=locked(id); expire(t); if(t.getStatus()!=TableStatus.AVAILABLE)throw new BusinessRuleException("This table is not available to hold."); int mins=r.minutes()==null?15:r.minutes(); t.setStatus(TableStatus.HELD);t.setHeldBy(user);t.setHeldAt(Instant.now());t.setHoldExpiresAt(Instant.now().plus(Duration.ofMinutes(mins)));t.setHoldReason(trim(r.reason()));return table(t);}
 @Transactional public TableResponse release(Long id,String user){RestaurantTable t=locked(id);expire(t);if(t.getStatus()==TableStatus.HELD&&t.getHeldBy()!=null&&!t.getHeldBy().equals(user))throw new BusinessRuleException("This table is held by another user.");if(t.getStatus()==TableStatus.HELD){t.clearHold();t.setStatus(TableStatus.AVAILABLE);}return table(t);}
 @Transactional public ReservationResponse reserve(ReservationRequest r){if(!r.endsAt().isAfter(r.startsAt()))throw new BusinessRuleException("Reservation end time must be after start time.");RestaurantTable t=locked(r.tableId());if(!t.isActive()||t.getCapacity()<r.guestCount())throw new BusinessRuleException("Selected table cannot accommodate this reservation.");if(reservations.hasOverlap(t.getId(),r.startsAt(),r.endsAt()))throw new BusinessRuleException("This table is already reserved for the selected time. Please select another table.");Reservation x=new Reservation();x.setTable(t);x.setCustomerName(trim(r.customerName()));x.setPhone(trim(r.phone()));x.setStartsAt(r.startsAt());x.setEndsAt(r.endsAt());x.setGuestCount(r.guestCount());x.setNotes(trim(r.notes()));return reservation(reservations.save(x));}
 @Transactional(readOnly=true) public List<ReservationResponse> reservations(){return reservations.findAll().stream().map(this::reservation).toList();}
 @Transactional public RestaurantTable claimForOrder(Long tableId,String username){RestaurantTable t=locked(tableId);expire(t);if(!t.isActive()||t.getStatus()==TableStatus.OUT_OF_SERVICE||t.getStatus()==TableStatus.CLEANING||t.getStatus()==TableStatus.RESERVED||t.getStatus()==TableStatus.OCCUPIED)throw new BusinessRuleException("Selected table is unavailable.");if(t.getStatus()==TableStatus.HELD&&!username.equals(t.getHeldBy()))throw new BusinessRuleException("Selected table is held by another user.");t.clearHold();t.setStatus(TableStatus.OCCUPIED);return t;}
 @Transactional public void releaseAfterOrder(RestaurantTable table){ if(table!=null&&table.getStatus()==TableStatus.OCCUPIED){table.clearHold();table.setStatus(TableStatus.AVAILABLE);} }
 private void apply(RestaurantTable t,TableRequest r,boolean allowStatus){t.setTableNumber(r.tableNumber().trim());t.setTableName(trim(r.tableName())==null?r.tableNumber().trim():trim(r.tableName()));t.setCapacity(r.capacity());t.setTableType(trim(r.tableType())==null?type(r.capacity()):trim(r.tableType()));t.setSection(trim(r.section()));if(allowStatus&&r.status()!=null)t.setStatus(r.status());if(r.active()!=null)t.setActive(r.active());}
 private boolean hasActiveOrder(RestaurantTable t){return t.getStatus()==TableStatus.OCCUPIED;} private String type(int c){return c<=2?"Couple":c<=4?"Family":c<=6?"Group":c<=12?"Large Group":"Party";} private RestaurantTable find(Long id){return tables.findById(id).orElseThrow(()->new ResourceNotFoundException("Table not found: "+id));}private RestaurantTable locked(Long id){return tables.findByIdForUpdate(id).orElseThrow(()->new ResourceNotFoundException("Table not found: "+id));}private void expireHolds(){tables.findByActiveTrueOrderByTableNumberAsc().forEach(this::expire);}private void expire(RestaurantTable t){if(t.getStatus()==TableStatus.HELD&&t.getHoldExpiresAt()!=null&&!t.getHoldExpiresAt().isAfter(Instant.now())){t.clearHold();t.setStatus(TableStatus.AVAILABLE);}}private String trim(String v){return v==null||v.trim().isEmpty()?null:v.trim();}private TableResponse table(RestaurantTable t){var order=t.getStatus()==TableStatus.OCCUPIED?orders.findFirstByRestaurantTableIdAndStatusNotOrderByCreatedAtDesc(t.getId(),OrderStatus.CANCELLED).orElse(null):null;return new TableResponse(t.getId(),t.getTableNumber(),t.getTableName(),t.getCapacity(),t.getTableType(),t.getSection(),t.getStatus(),t.isActive(),t.getHeldBy(),t.getHeldAt(),t.getHoldExpiresAt(),t.getHoldReason(),order==null?null:order.getId(),order==null?null:order.getOrderNumber(),order==null?null:order.getCustomerName(),order==null?null:order.getLines().size(),order==null?null:order.getTotalAmount(),order==null?null:order.getCreatedAt());}private ReservationResponse reservation(Reservation r){return new ReservationResponse(r.getId(),r.getTable().getId(),r.getTable().getTableNumber(),r.getCustomerName(),r.getPhone(),r.getStartsAt(),r.getEndsAt(),r.getGuestCount(),r.getStatus(),r.getNotes());}
}
